server:
  port: 8081

spring:
  application:
    name: document-metadata-service

  datasource:
    url: jdbc:mysql://localhost:3306/dms?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Abhishek@2002
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
