// Model representing a Document entity in the system
export interface Document {
  id?: number;          // Unique identifier (auto-generated by backend)
  title: string;        // Title of the document (required)
  description?: string; // Optional description of the document
  fileName?: string;    // Original uploaded file name
  fileSize?: number;    // Size of the file in bytes
  uploadDate?: string;  // Date when the file was uploaded
  uploadedBy?: string;  // Name/ID of the uploader
  fileId?: string;      // Unique file ID used by file storage for chunked upload
  totalChunks?: number; // Number of chunks the file was split into for upload
}
